return {
    master_strength = 100,
    heavy_hold_ms = 90,
    light_hold_ms = 60,
    heavy_floor = 15,
    light_floor = 8,
    onset_supplement = true,
    onset_supplement_ms = 60,
    onset_supplement_level = 35,
    kick_mode = "multiplicative",
    kick_amount = 35,
    kick_window_ms = 25,
    spinup_assist = true,
    assist_window_ms = 30,
    flame_enabled = true,
    score_scaling_enabled = false,
    debug_log = false,
}
